# Generated by Django 4.2 on 2026-04-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sensitive_note',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
