# Generated by Django 4.2 on 2026-04-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_alter_profile_sensitive_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sensitive_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
